#include "TemperatureMonitor.h"
#include <message.h>

configuration TemperatureMonitorAppC {
}
implementation {

  components TemperatureMonitorC as App;
  App.Boot -> MainC;
  
  components MainC;
  
  /* Timer which defines instants in which a new threshold value is generated by the sink node */
  components new TimerMilliC() as TimerGenerateNewThreshold;
  App.TimerGenerateNewThreshold -> TimerGenerateNewThreshold;
  
  /* Timer which defines instants in which the non-sink nodes measure the temperature */
  components new TimerMilliC() as TimerMeasureTemperature;
  App.TimerMeasureTemperature -> TimerMeasureTemperature;
  
  /* Node communication components */
  components ActiveMessageC, new AMSenderC(AM_TEMPERATURE_MONITOR), new AMReceiverC(AM_TEMPERATURE_MONITOR);
  App.AMSend -> AMSenderC;
  App.Receive -> AMReceiverC;
  App.Packet -> AMSenderC;
  App.AMPacket -> AMSenderC;
  App.AMControl -> ActiveMessageC;
  
  /* Generic component which represents a sensor (in our case a temperature sensor) */
  components new DemoSensorC();
  App.Temperature -> DemoSensorC;
  

  
}
